version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_dashboard"
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=${VITE_API_URL}
    networks:
      my_custom_network:
        ipv4_address: ${DASHBOARD_IP}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  my_custom_network:
    external: true
